src/bundle/Entity/Entity.php
<?php

namespace ContextualCode\EzPlatformContentVariablesBundle\Entity;

abstract class Entity
{
    public function getId(): ?int
    {
        return null;
    }

    public function isNew(): bool
    {
        return $this->getId() === null;
    }

    public function canBeDeleted(): bool
    {
        return false;
    }
}

src/bundle/Entity/Variable.php
<?php

namespace ContextualCode\EzPlatformContentVariablesBundle\Entity;

use ContextualCode\EzPlatformContentVariablesBundle\EventSubscriber\ContentVariablesOutputFilter;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="cc_content_variable")
 * @UniqueEntity("identifier")
 */
class Variable extends Entity
{
    private const VALUE_TYPE_STATIC = 1;
    private const VALUE_TYPE_CALLBACK = 2;
    private const VALUE_STATIC_PLACEHOLDER = 'empty-value-placeholder';

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Collection", inversedBy="contentVariables")
     * @ORM\JoinColumn(name="collection_id", referencedColumnName="id")
     */
    private $collection;

    /**
     * @ORM\Column(type="string", length=256, unique=true)
     * @Assert\NotBlank()
     * @Assert\Regex(
     *     pattern="/^[[:alnum:]_]+$/",
     *     message="variable.identifier"
     * )
     */
    private $identifier;

    /**
     * @ORM\Column(type="string", length=256)
     */
    private $name;

    /**
     * @ORM\Column(type="smallint", length=1, nullable=true)
     */
    private $valueType;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private $valueStatic;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private $valueCallback;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $priority = 0;

    /** @var int */
    private $linkedContentCount = 0;

    public function __construct()
    {
        $this->valueType = self::VALUE_TYPE_STATIC;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCollection(): ?Collection
    {
        return $this->collection;
    }

    public function setCollection(?Collection $collection): void
    {
        $this->collection = $collection;
    }

    public function getIdentifier(): ?string
    {
        return $this->identifier;
    }

    public function setIdentifier(?string $identifier): void
    {
        $this->identifier = $identifier;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    public function getValueType(): ?int
    {
        return $this->valueType;
    }

    public function setValueType(?int $valueType): void
    {
        $this->valueType = $valueType;
    }

    public function getValueStatic(): ?string
    {
        return $this->valueStatic;
    }

    public function setValueStatic(?string $valueStatic): void
    {
        $this->valueStatic = $valueStatic;
    }

    public function getValueCallback(): ?string
    {
        return $this->valueCallback;
    }

    public function setValueCallback(?string $valueCallback): void
    {
        $this->valueCallback = $valueCallback;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?string $priority): void
    {
        $this->priority = $priority;
    }

    public function canBeDeleted(): bool
    {
        return $this->getLinkedContentCount() === 0;
    }

    public function isStatic(): bool
    {
        return $this->getValueType() === self::VALUE_TYPE_STATIC;
    }

    public function getLinkedContentCount(): int
    {
        return $this->linkedContentCount;
    }

    public function setLinkedContentCount(int $count): void
    {
        $this->linkedContentCount = $count;
    }

    public function getPlaceholder(): ?string
    {
        $identifier = $this->getIdentifier();
        if (!$identifier) {
            return null;
        }

        return ContentVariablesOutputFilter::WRAPPER . $identifier . ContentVariablesOutputFilter::WRAPPER;
    }

    public function setStaticValuePlaceholder(): void
    {
        if (
            $this->getValueType() === self::VALUE_TYPE_CALLBACK
            && empty($this->getValueStatic())
        ) {
            $this->setValueStatic(self::VALUE_STATIC_PLACEHOLDER);
        }
    }

    public function fixStaticValuePlaceholder(): void
    {
        if (
            $this->getValueType() === self::VALUE_TYPE_CALLBACK
            && $this->getValueStatic() === self::VALUE_STATIC_PLACEHOLDER
        ) {
            $this->setValueStatic(null);
        }
    }

    public function makeStatic(): void
    {
        $this->setValueType(self::VALUE_TYPE_STATIC);
        $this->setValueCallback(null);
    }

    public static function getValueTypes(): array
    {
        return [
            self::VALUE_TYPE_STATIC,
            self::VALUE_TYPE_CALLBACK,
        ];
    }
}

src/bundle/Form/Data/ItemsSelection.php
<?php

namespace ContextualCode\EzPlatformContentVariablesBundle\Form\Data;

use ContextualCode\EzPlatformContentVariablesBundle\Entity\Entity;

class ItemsSelection extends Collection
{
    protected $selectedIds = [];
    protected $action;
    protected $possibleActions = ['updatePriority', 'delete'];

    public function __construct(array $items = [])
    {
        parent::__construct($items);

        $ids = array_keys($this->items);
        foreach ($ids as $id) {
            $this->selectedIds[$id] = false;
        }

        $this->action = $this->possibleActions[0];
    }

    public function getSelectedId(): array
    {
        return $this->selectedIds;
    }

    public function setSelectedId(array $data): void
    {
        $this->selectedIds = $data;
    }

    public function getPriority(): array
    {
        return $this->getItemsProperty('priority');
    }

    public function setPriority(array $data): void
    {
        $this->setItemsProperty($data, 'priority');
    }

    /**
     * @return Entity[]
     */
    public function getSelectedItems(): array
    {
        $return = [];
        foreach ($this->getSelectedId() as $id => $isSelected) {
            if ($isSelected && isset($this->items[$id])) {
                $return[] = $this->items[$id];
            }
        }

        return $return;
    }

    public function getAction(): string
    {
        return $this->action;
    }

    public function setAction(string $action): void
    {
        $this->action = $action;
    }

    public function isActionValid(): bool
    {
        return in_array($this->getAction(), $this->possibleActions, true);
    }
}

src/bundle/Form/Type/Variable/BulkActions.php
<?php

namespace ContextualCode\EzPlatformContentVariablesBundle\Form\Type\Variable;

use ContextualCode\EzPlatformContentVariablesBundle\Form\Type\BulkActions as Base;

class BulkActions extends Base
{
}

src/bundle/Form/Type/Variable/BulkEdit.php
<?php

namespace ContextualCode\EzPlatformContentVariablesBundle\Form\Type\Variable;

use ContextualCode\EzPlatformContentVariables\Variable\Value\Processor;
use ContextualCode\EzPlatformContentVariablesBundle\Form\Data\VariableValues;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BulkEdit extends AbstractType
{
    /** @var Processor */
    protected $callbackProcessor;

    public function __construct(Processor $callbackProcessor)
    {
        $this->callbackProcessor = $callbackProcessor;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $callbacks = $this->callbackProcessor->getCallbackChoices();

        $builder
            ->add('valueStatic', CollectionType::class, [
                'label' => false,
                'entry_options' => [
                    'label' => false,
                ],
            ]);

        if (count($callbacks) > 0) {
            $builder
                ->add('valueCallback', CollectionType::class, [
                    'entry_type' => ChoiceType::class,
                    'label' => false,
                    'entry_options' => [
                        'label' => false,
                        'choices' => $callbacks,
                    ],
                ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => VariableValues::class,
            'translation_domain' => 'forms',
        ]);
    }
}

src/bundle/Form/Type/Variable/Edit.php
<?php

namespace ContextualCode\EzPlatformContentVariablesBundle\Form\Type\Variable;

use ContextualCode\EzPlatformContentVariables\Variable\Value\Processor;
use ContextualCode\EzPlatformContentVariablesBundle\Entity\Variable as DataClass;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Edit extends AbstractType
{
    /** @var Processor */
    protected $callbackProcessor;

    public function __construct(Processor $callbackProcessor)
    {
        $this->callbackProcessor = $callbackProcessor;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $callbacks = $this->callbackProcessor->getCallbackChoices();

        $builder
            ->add('name')
            ->add('identifier', null, ['attr' => [
                'readonly' => !$options['is_new'],
            ]]);

        if (count($callbacks) > 0) {
            $builder
                ->add('valueType', ChoiceType::class, [
                    'choices' => DataClass::getValueTypes(),
                    'choice_label' => static function ($choice, $key, $value) {
                        return 'variable.value_type.' . $value;
                    },
                    'choice_translation_domain' => 'content_variables',
                ])
                ->add('valueCallback', ChoiceType::class, ['choices' => $callbacks]);
        }

        $builder->add('valueStatic', null, ['required' => true]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setRequired('is_new');
        $resolver->setDefaults(['data_class' => DataClass::class]);
    }
}

src/bundle/Controller/VariableController.php
<?php

namespace ContextualCode\EzPlatformContentVariablesBundle\Controller;

use eZ\Publish\API\Repository\Values\Content\VersionInfo;
use ContextualCode\EzPlatformContentVariablesBundle\Entity\Collection;
use ContextualCode\EzPlatformContentVariablesBundle\Entity\Variable;
use ContextualCode\EzPlatformContentVariablesBundle\Form\Data\VariableValues;
use ContextualCode\EzPlatformContentVariablesBundle\Service\Handler\Handler as EntityHandler;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/content_variables", name="content_variables.")
 */
class VariableController extends BaseController
{
    private const BULK_EDIT_COLLAPSED_COLLECTIONS_COOKIE_VAR = 'content-variables_bulk-edit_collapsed-collections';
    private const BULK_EDIT_COLLAPSED_COLLECTIONS_COOKIE_SEPARATOR = ',';

    protected $entityName = 'variable';

    protected function getEntityHandler(): EntityHandler
    {
        return $this->variableHandler;
    }

    /**
     * @Route("/{id}/variables", name="list", defaults={"id"=null})
     */
    public function listAction(Request $request, Collection $collection): Response
    {
        $collectionVariables = $this->variableHandler->findByCollection($collection);
        $pagination = $this->getPagination($request, $collectionVariables);

        $variables = $pagination->getCurrentPageResults();
        foreach ($variables as $variable) {
            $this->variableHandler->countLinkedContent($variable);
        }

        $form = $this->formFactory->variablesBulkActions($variables);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $result = $this->handleBulkAction($form);
            if ($result instanceof Response) {
                return $result;
            }

            return $this->redirectToRoute('content_variables.list', ['id' => $collection->getId()]);
        }

        $params = [
            'pager' => $pagination,
            'variables' => $variables,
            'collection' => $collection,
            'form' => $form->createView(),
        ];

        return $this->render('@ezdesign/content_variable/variable/list.html.twig', $params);
    }

    /**
     * @Route("/{id}/new", name="new", defaults={"id"=null}, requirements={"id"="\d+"})
     */
    public function createAction(Request $request, Collection $collection): Response
    {
        return $this->editAction($request, new Variable(), $collection);
    }

    /**
     * @Route("/edit/{id}", name="edit", defaults={"id"=null})
     */
    public function editAction(
        Request $request,
        Variable $variable,
        Collection $collection = null
    ): Response {
        if ($collection === null) {
            $collection = $variable->getCollection();
        }

        if ($this->variableHandler->missingCallbackToStatic($variable)) {
            $message = $this->getTranslatedMessage('variable.missing_callback.warning');
            $this->notificationHandler->warning($message);
        }

        $form = $this->formFactory->variablesEdit($variable);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $message = $this->getEditMessage($variable);

            if ($variable->getCollection() === null) {
                $variable->setCollection($collection);
            }

            $this->variableHandler->persist($variable);
            $this->notificationHandler->success($message);

            return $this->redirectToRoute('content_variables.list', ['id' => $collection->getId()]);
        }

        $params = [
            'form' => $form->createView(),
            'variable' => $variable,
            'collection' => $collection,
        ];

        return $this->render('@ezdesign/content_variable/variable/edit.html.twig', $params);
    }

    /**
     * @Route("/{id}/linked_content", name="linked_content", defaults={"id"=null}, requirements={"id"="\d+"})
     */
    public function linkedContentAction(Variable $variable): Response
    {
        $linkedContentInfo = $this->variableHandler->linkedContentInfoGrouped($variable);

        $params = [
            'variable' => $variable,
            'linked_content' => $linkedContentInfo,
        ];

        return $this->render('@ezdesign/content_variable/variable/related_content.html.twig', $params);
    }

    /**
     * @Route("/bulk_edit", name="bulk_edit")
     */
    public function bulkEditAction(Request $request): Response
    {
        $collections = $this->collectionHandler->findAll();
        $variables = $this->variableHandler->findAll();
        $form = $this->formFactory->variablesBulkEdit($variables);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $result = $this->submitHandler->handle($form, [$this, 'bulkEditHandler']);
            if ($result instanceof Response) {
                return $result;
            }
        }

        $params = [
            'collections' => $collections,
            'form' => $form->createView(),
            'collapsed_collections' => $this->getBulkEditCollapsedCollections($request),
        ];

        return $this->render('@ezdesign/content_variable/variable/bulk_edit.html.twig', $params);
    }

    public function bulkEditHandler(VariableValues $data): void
    {
        foreach ($data->getEditedItems() as $variable) {
            $this->variableHandler->persist($variable);
            $this->sendSuccessMessage($variable, 'edit');
        }
    }

    protected function getBulkEditCollapsedCollections(Request $request): array
    {
        $var = self::BULK_EDIT_COLLAPSED_COLLECTIONS_COOKIE_VAR;
        $separator = self::BULK_EDIT_COLLAPSED_COLLECTIONS_COOKIE_SEPARATOR;

        $ids = explode($separator, $request->cookies->get($var, null));
        foreach ($ids as $k => $id) {
            $ids[$k] = (int) $id;
        }

        return [
            'ids' => $ids,
            'cookie_var' => $var,
            'cookie_separator' => $separator,
        ];
    }
}

src/bundle/Resources/views/themes/standard/content_variable/variable/bulk_edit.html.twig
{% extends '@ezdesign/content_variable/layout.html.twig' %}
{% set show_left_sidebar = true %}

{% trans_default_domain "content_variables" %}

{% block content %}
    <div class="row align-items-stretch ez-main-row">
        {% block left_sidebar %}
            {{ parent() }}
        {% endblock left_sidebar %}

        <div class="px-0 pb-4 ez-content-container">
            <div class="ez-header">
                <div class="container">
                    {% include '@ezdesign/ui/breadcrumbs.html.twig' with { items: [
                        { value: 'path.root'|trans, url: path('content_variables.collection.list') },
                        { value: 'path.bulk_edit'|trans }
                    ]} %}
                    {% include '@ezdesign/content_variable/parts/page_title.html.twig' with {
                        title: 'title.bulk_edit'|trans,
                        iconsFile: 'bundles/ezplatformcontentvariables/img/icons.svg',
                        iconName: 'edit-bulk',
                    } %}
                </div>
            </div>

            <section class="container mt-4 px-5">
                {% if collections|length > 0 %}
                    {{ form_start(form) }}
                    {{ form_errors(form) }}

                    {% for collection in collections %}
                        {% set hasVariables = collection.contentVariables|length > 0 %}
                        {% set isCollapsed = collection.id in collapsed_collections.ids %}
                        <div class="ez-table-header">
                            <div class="ez-table-header__headline">{{ collection.name }}</div>
                            {% if collection.description %}
                                <div class="c-no-items">{{ collection.description }}</div>
                            {% endif %}
                            <div>
                                {% include '@ezdesign/content_variable/buttons/collapse.html.twig' with {
                                    'containerId': 'content-variables-bulk-edit-' ~ collection.id,
                                    'isCollapsed': isCollapsed,
                                    'cookieVariable': collapsed_collections.cookie_var,
                                    'cookieSeparator': collapsed_collections.cookie_separator,
                                    'itemId': collection.id,
                                } %}
                            </div>
                        </div>
                        <div id="content-variables-bulk-edit-{{ collection.id }}" class="{{ isCollapsed ? 'collapse' : 'show' }}">
                            {% if hasVariables %}
                                <table class="ez-table table mb-0">
                                    <thead>
                                        <tr>
                                            <th>{{ 'variable.name'|trans }}</th>
                                            <th>{{ 'variable.placeholder'|trans }}</th>
                                            <th>{{ 'variable.value'|trans }}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for variable in collection.contentVariables %}
                                        <tr class="content-variable-block">
                                            <td class="ez-table__cell">{{ variable.name }}</td>
                                            <td class="ez-table__cell">{{ variable.placeholder }}</td>
                                            <td class="ez-table__cell">
                                                <div{% if not variable.isStatic %} hidden="hidden"{% endif %}>
                                                    {{ form_widget(form.valueStatic[variable.id], {
                                                        'attr': {'class': 'form-control content-variable-value-static'}
                                                    }) }}
                                                </div>
                                                {% if form.valueCallback is defined %}
                                                    <div{% if variable.isStatic %} hidden="hidden"{% endif %}>
                                                        {{ form_widget(form.valueCallback[variable.id], {
                                                            'attr': {'class': 'form-control content-variable-value-callback'}
                                                        }) }}
                                                    </div>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <p class="ez-table-no-content mb-0">{{ 'variable.no_items'|trans }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <button id="variables-update" type="submit" hidden />
                    {{ form_end(form) }}
                {% else %}
                    <p class="ez-table-no-content">{{ 'bulk_edit.no_items'|trans({'%link_start%' : '<a href="'~path('content_variables.collection.new')~'">', '%link_end%' : '</a>'})|raw }}</p>
                {% endif %}
            </section>
        </div>

        <div class="pt-4 px-0 bg-secondary ez-context-menu">
            <div class="ez-sticky-container">
                {% set sidebar_right = knp_menu_get('content_variables.menu.bulk_edit.sidebar_right', [], {}) %}
                {{ knp_menu_render(sidebar_right, {
                    'template': '@ezdesign/ui/menu/sidebar_right.html.twig'
                }) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('ezplatform-content-variables-bulk-edit-css', null, 'ezplatform') }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('ezplatform-content-variables-bulk-edit-js', null, 'ezplatform') }}
{% endblock %}

src/bundle/Resources/views/themes/standard/content_variable/variable/list.html.twig
{% extends '@ezdesign/content_variable/layout.html.twig' %}
{% set show_left_sidebar = true %}

{% trans_default_domain "content_variables" %}

{% block content %}
    <div class="row align-items-stretch ez-main-row">
        {% block left_sidebar %}
            {{ parent() }}
        {% endblock left_sidebar %}

        <div class="px-0 pb-4 ez-content-container">
            <div class="ez-header">
                <div class="container">
                    {% include '@ezdesign/ui/breadcrumbs.html.twig' with { items: [
                        { value: 'path.root'|trans, url: path('content_variables.collection.list') },
                        { value: collection.name }
                    ]} %}
                    {% include '@ezdesign/ui/page_title.html.twig' with {
                        title: collection.name,
                        iconName: 'keyword'
                    } %}
                </div>
            </div>

            {% set form_id = 'variables_bulk_actions' %}
            <section class="container mt-4 px-5">
                <div class="ez-table-header">
                    <div class="ez-table-header__headline">{{ 'title.variables'|trans }}</div>
                    <div>
                        {% include '@ezdesign/content_variable/buttons/new.html.twig' with {
                            'title': 'variables.new'|trans,
                            'href': path('content_variables.new', {'id': collection.id}),
                        } %}
                        {% if variables|length > 0 %}
                            {% include '@ezdesign/content_variable/buttons/update_priority.html.twig' with {
                                'title': 'variable.update_priority'|trans,
                                'id': 'update-priority-variables',
                                'form_id': form_id,
                                'action': 'updatePriority',
                            } %}
                            {% include '@ezdesign/content_variable/buttons/delete.html.twig' with {
                                'title': 'variable.delete'|trans,
                                'id': 'delete-variables',
                                'form_id': form_id,
                                'action': 'delete',
                                'modal_data_target': 'delete-variables-modal',
                                'message': 'variable.delete.modal.message'|trans,
                            } %}
                        {% endif %}
                    </div>
                </div>

                {% if variables|length > 0 %}
                    {{ form_start(form, {
                        'attr': {
                            'class': 'ez-toggle-btn-state',
                            'data-toggle-button-id': '#delete-variables',
                            'id': form_id
                        }
                    }) }}
                    <table class="ez-table table mb-3">
                        <thead>
                            <tr>
                                <th class="ez-table__cell--has-checkbox"><input type="checkbox" /></th>
                                <th>{{ 'variable.name'|trans }}</th>
                                <th>{{ 'variable.identifier'|trans }}</th>
                                <th>{{ 'variable.priority'|trans }}</th>
                                <th>{{ 'variable.content'|trans }}</th>
                                <th>{{ 'variable.value'|trans }}</th>
                                <th/>
                            </tr>
                        </thead>
                        <tbody>
                        {% for variable in variables %}
                            <tr>
                                <td class="ez-table__cell ez-table__cell--has-checkbox">
                                    {{ form_widget(form.selectedId[variable.id], {"disabled": not variable.canBeDeleted}) }}
                                </td>
                                <td class="ez-table__cell">{{ variable.name }}</td>
                                <td class="ez-table__cell">{{ variable.identifier }}</td>
                                <td class="ez-table__cell">
                                    <div class="c-table-view-item__inner-wrapper--input">
                                        {{ form_widget(form.priority[variable.id], {
                                            'attr': {'class': 'form-control content-variable-priority-value'}
                                        }) }}
                                    </div>
                                </td>
                                <td class="ez-table__cell">
                                    <a href="{{ path('content_variables.linked_content', {'id': variable.id}) }}">{{ variable.getLinkedContentCount }}</a>
                                </td>
                                <td class="ez-table__cell">
                                    {% if variable.isStatic %}
                                        {{ variable.valueStatic }}
                                    {% else %}
                                        {{ 'variable.value.callback'|trans({'%callback%': variable.valueCallback}) }}
                                    {% endif %}
                                </td>
                                <td class="ez-table__cell ez-table__cell--has-action-btns text-right">
                                    {% include '@ezdesign/content_variable/buttons/linked_content.html.twig' with {
                                        'title': 'variable.content'|trans,
                                        'href': path('content_variables.linked_content', {'id': variable.id}),
                                    } %}
                                    {% include '@ezdesign/content_variable/buttons/edit.html.twig' with {
                                        'title': 'variable.edit'|trans({'%name%': collection.name|u.truncate(50) }),
                                        'href': path('content_variables.edit', {'id': variable.id}),
                                    } %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {{ form_end(form) }}
                    <div class="row justify-content-center align-items-center mb-2">
                        <span class="ez-pagination__text">
                            {{ 'pagination.viewing'|trans({
                                '%viewing%': pager.currentPageResults|length,
                                '%total%': pager.nbResults}, 'pagination')|raw }}
                        </span>
                    </div>
                    {% if pager.haveToPaginate %}
                        <div class="row justify-content-center align-items-center ez-pagination__btn mb-5">
                            {{ pagerfanta(pager, 'ez') }}
                        </div>
                    {% endif %}
                {% else %}
                    <p class="ez-table-no-content">{{ 'variable.no_items'|trans }}</p>
                {% endif %}
            </section>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('ezplatform-content-variables-variables-list-js', null, 'ezplatform') }}
{% endblock %}